import { SeoCost, usd } from './SeoCost';
import { useEffect, useState } from 'react';
import { Activity, ArrowUpRight, Check, ChevronRight, Globe2, KeyRound, Plus, RefreshCw, Search, ShieldCheck, Trash2, TrendingUp } from 'lucide-react';
const date=(s?:string)=>s?new Date(s).toLocaleString('de-CH',{dateStyle:'short',timeStyle:'short'}):'Noch nicht gemessen';
const seconds=(n:any)=>typeof n==='number'?`${(n/1000).toFixed(2)} s`:'—';
function RankingAccessNotice({data}:{data:any}){return data?.rankAccess?.ok===false?<div className="seo-notice seo-error"><div><strong>Ranking-Abfrage noch nicht freigegeben</strong><p>{data.rankAccess.message}</p>{data.rankAccess.providerCode===40104&&<a className="seo-source" href="https://app.dataforseo.com/" target="_blank" rel="noopener noreferrer">DataForSEO-Konto verifizieren<ArrowUpRight size={12}/></a>}<small>Letzte Ranking-Antwort: {date(data.rankAccess.at)}. Nach Behebung erneut messen.</small></div></div>:null;}
type Shared={data:any; busy:string; request:(r:string,b?:any,m?:string)=>Promise<any>; act:(l:string,f:()=>Promise<any>,s:string)=>Promise<void>};
export function MetricChart({points,ranking=false,depth=100}:{points:{at:string,value:number|null}[];ranking?:boolean;depth?:number}){
 if(!points.length)return <div className="seo-chart-empty"><Activity size={24}/><strong>Noch keine Messreihe</strong><span>Der Verlauf entsteht aus echten, gespeicherten Messungen.</span></div>;
 const max=ranking?depth:100,min=ranking?1:0,width=450,height=106;
 const xy=(p:any,i:number)=>[38+(points.length===1?width/2:i/(points.length-1)*width),14+(ranking?(p.value-min)/(max-min):1-p.value/100)*height];
 const segments:string[]=[];let segment:string[]=[];
 points.forEach((p,i)=>{if(p.value===null){if(segment.length)segments.push(segment.join(' '));segment=[];}else segment.push(xy(p,i).join(','));});if(segment.length)segments.push(segment.join(' '));
 return <><svg className="seo-metric-chart" viewBox="0 0 510 154" role="img" aria-label={ranking?'Gemessene organische Google-Positionen. Kleinere Zahl ist besser.':'Verlauf des technischen Health-Scores von 0 bis 100.'}>
  {[0,.5,1].map(t=><g key={t}><line x1="38" x2="488" y1={14+t*height} y2={14+t*height}/><text x="3" y={18+t*height}>{Math.round(ranking?1+t*(max-1):100-t*100)}</text></g>)}
  {segments.map((s,i)=><polyline key={i} points={s} fill="none" className="seo-chart-line"/>)}
  {points.map((p,i)=>p.value===null?null:<circle key={i} cx={xy(p,i)[0]} cy={xy(p,i)[1]} r="4" className="seo-chart-point"><title>{date(p.at)}: {ranking?'Position ':''}{p.value}</title></circle>)}
  <text x="38" y="148">{new Date(points[0].at).toLocaleDateString('de-CH')}</text><text x="488" y="148" textAnchor="end">{new Date(points[points.length-1].at).toLocaleDateString('de-CH')}</text>
 </svg><details className="seo-chart-values"><summary>Messwerte als Tabelle</summary><table><thead><tr><th>Zeitpunkt</th><th>{ranking?'Position':'Health'}</th></tr></thead><tbody>{points.map((p,i)=><tr key={i}><td>{date(p.at)}</td><td>{p.value??'Im erfassten Bereich nicht gefunden'}</td></tr>)}</tbody></table></details>{points.length===1&&<small>Erste Messung gespeichert. Weitere Durchläufe ergänzen den Verlauf.</small>}</>;
}
export function SeoHealthDashboard({data,busy,request,act}:Shared){
 const health=data?.health?.[0],job=data?.job;
 const pending=job?.state==='queued'||job?.state==='running';
 const score=health?.score;
 const healthLabel=score===undefined||score===null?'Noch offen':score>=85?'Gute Basis':score>=60?'Verbesserbar':'Handlungsbedarf';
 const issues=health?.pages?.flatMap((p:any)=>p.issues.map((label:string)=>({path:p.path,label})))||[];
 return <>
  <div className="seo-section-heading"><div><span className="seo-eyebrow">MESSEN. VERSTEHEN. VERBESSERN.</span><h2>Website-Gesundheit</h2></div><span className="seo-chip">{data?.config.healthDaily?'Täglicher Check':'Manuell'}</span></div>
  <section className="seo-health-hero"><div className="seo-health-ring"><svg viewBox="0 0 140 140" role="img" aria-label={`Technischer Health-Score: ${score??'noch nicht gemessen'}`}><circle cx="70" cy="70" r="59" className="seo-ring-track"/><circle cx="70" cy="70" r="59" className="seo-ring-value" strokeDasharray={`${(score||0)/100*371} 371`} transform="rotate(-90 70 70)"/></svg><div><strong>{score??'—'}</strong><span>HEALTH / 100</span></div></div><div className="seo-health-summary"><span className="seo-chip">{healthLabel}</span><h3>{health?`${health.pages.length} Seiten geprüft`:'Der erste Scan wartet'}</h3><p>{health?'Technik, Inhalte und mobile Darstellung – aus echten Seitenprüfungen.':'Starte einen vollständigen Check deiner öffentlichen Inhaltsseiten.'}</p><small>{date(health?.at)}</small></div></section>
  <div className="seo-stat-grid"><div><small>Offene Hinweise</small><strong>{health?.issueCount??'—'}</strong><span>Einzelne fehlgeschlagene Checks</span></div><div><small>Nicht erreichbar / geladen</small><strong>{health?.unavailable??'—'}</strong><span>Im letzten Scan</span></div><div><small>LCP · Median</small><strong>{seconds(health?.medianLcp)}</strong><span>Mobiler Labortest · Ziel ≤ 2,5 s</span></div><div><small>TTFB · Median</small><strong>{seconds(health?.medianTtfb)}</strong><span>Antwortbeginn vom VPS aus</span></div></div>
  <button className="seo-primary seo-wide" disabled={!!busy||pending} onClick={()=>act('Website-Scan einplanen',()=>request('monitor/scan',{}),'Scan eingeplant. Er startet innerhalb einer Minute und benötigt einige Minuten.')}><RefreshCw size={16}/>{pending?(job.state==='queued'?'Scan wartet auf Ausführung':'Website wird geprüft …'):'Website jetzt vollständig prüfen'}</button>
  {pending&&<p className="seo-footnote" role="status">Du kannst das Panel schließen. Der Scan läuft auf dem VPS weiter; diese Ansicht aktualisiert sich automatisch.</p>}
  {job?.state==='failed'&&<div className="seo-notice seo-error">{job.error}</div>}
  <p className="seo-footnote">Eigene technische Checkliste, kein Google-Score und keine Rankingprognose. LCP/CLS sind einzelne Labormessungen ohne Netzwerkdrosselung, keine Core-Web-Vitals-Felddaten.</p>
  <section className="seo-card"><h3>robots.txt & Sitemap</h3><p>Das SEO-System erstellt beide Dateien auf dem VPS und aktualisiert die Sitemap nach vollständigen Website-Scans. Sie enthält nur geprüfte öffentliche Seiten ohne noindex-Anweisung.</p><div className="seo-actions"><a className="seo-source" href={`${window.location.origin}/robots.txt` } target="_blank" rel="noopener noreferrer">robots.txt öffnen<ArrowUpRight size={12}/></a><a className="seo-source" href={`${window.location.origin}/sitemap.xml` } target="_blank" rel="noopener noreferrer">sitemap.xml öffnen<ArrowUpRight size={12}/></a></div><small>Die Prüfung oben zeigt den Stand des letzten Scans. Neue Seiten werden beim nächsten vollständigen Scan berücksichtigt. Kein zusätzliches API-Guthaben nötig.</small></section>
  {health&&<><section className="seo-card"><h3>Wo steht die Webseite?</h3><div className="seo-category-bars">{[['crawl','Abruf & Indexierbarkeit'],['content','Titel & Inhalte'],['mobile','Mobile Darstellung']].map(([key,label])=><div key={key}><div><span>{label}</span><strong>{health.categories[key]??'—'}%</strong></div><div className="seo-meter"><i style={{width:`${health.categories[key]||0}%`}}/></div></div>)}</div><div className="seo-health-flags"><span className={health.site.robotsTxt?'seo-success-text':'seo-danger-text'}>robots.txt {health.site.robotsTxt?'erkannt':'nicht erkannt'}</span><span className={health.site.sitemap?'seo-success-text':'seo-danger-text'}>sitemap.xml {health.site.sitemap?'erkannt':'nicht erkannt'}</span></div><small>„Indexierbar“ heißt technisch nicht blockiert. Ob Google eine URL tatsächlich indexiert, ist damit nicht bestätigt.</small></section>
  <section className="seo-card"><div className="seo-card-title"><TrendingUp size={18}/><h3>Health-Verlauf</h3><span className="seo-chip">Letzte 30 Scans</span></div><MetricChart points={[...data.health].reverse().map((h:any)=>({at:h.at,value:h.score}))}/></section>
  <section className="seo-card"><h3>Seiten im Detail</h3>{health.site.truncated&&<p>Der Scan ist auf 40 Seiten begrenzt. {health.site.discovered} URLs wurden entdeckt; die Auswertung ist ein Ausschnitt.</p>}<div className="seo-page-health">{health.pages.map((p:any)=><details key={p.path}><summary><span>{p.path}</span><strong>{p.score}/100</strong></summary><p>{p.status?`HTTP ${p.status}`:'Kein HTTP-Ergebnis'} · LCP {seconds(p.lcpMs)} · CLS {p.cls===null?'—':p.cls?.toFixed(3)}</p>{p.error&&<p>{p.error}</p>}<ul className="seo-checks">{p.checks.map((c:any)=><li key={c.label}><span className={c.ok?'seo-pass':'seo-fail'}>{c.ok?'✓':'!'}</span>{c.label}</li>)}</ul><a className="seo-source" href={`${window.location.origin}${p.path}`} target="_blank" rel="noopener noreferrer">Seite öffnen<ArrowUpRight size={12}/></a></details>)}</div></section>
  {issues.length>0&&<div className="seo-footnote">Die technischen Hinweise werden separat behandelt. Ein höherer Checklistenwert allein garantiert keine bessere Google-Position.</div>}
  </>}
 </>;
}
export function SeoRankings({data,busy,request,act,onSettings,onAnalyze,pages}:Shared&{onSettings:()=>void;onAnalyze:(path:string)=>void;pages:any[]}){
 const [selected,setSelected]=useState('');
 const config=data?.config;const keyword=config?.keywords.find((k:any)=>k.id===selected)||config?.keywords[0];
 const scope=`${config?.location}|${config?.device}|de|${config?.depth}`;
 const records=(data?.rankings||[]).filter((r:any)=>r.keywordId===keyword?.id&&r.scope===scope);
 const latest=records[0],prev=records[1];
 const schedule=data?.schedule?.find((s:any)=>s.keywordId===keyword?.id);
 const measuredToday=!!latest&&latest.at.slice(0,10)===new Date().toISOString().slice(0,10);
 const nextManual=latest?new Date(Date.parse(latest.at.slice(0,10)+'T00:00:00Z')+86400000).toISOString():undefined;
 const difference=latest?.position&&prev?.position?prev.position-latest.position:null;
 const owned=pages.find((p:any)=>p.path===keyword?.path);
 const healthPage=data?.health?.[0]?.pages.find((p:any)=>p.path===keyword?.path);
 const ownTitle=owned?.published?.title||healthPage?.title;
 const ownDescription=owned?.published?.description||healthPage?.description;
 return <><div className="seo-section-heading"><div><span className="seo-eyebrow">GOOGLE · ORGANISCHE SUCHERGEBNISSE</span><h2>Rankings & Konkurrenz</h2></div><Globe2 size={23}/></div>
  <SeoRankingSettings data={data} busy={busy} request={request} act={act} pages={pages}/>
  <RankingAccessNotice data={data}/>
  {!data?.connected&&<section className="seo-card seo-highlight"><h3>Für echte Positionen verbinden</h3><p>Dein OpenAI-Schlüssel analysiert Inhalte. Google-Positionen und Top-10-Treffer benötigen zusätzlich eine Ranking-Datenquelle. Hier werden keine Positionen geschätzt oder erfunden.</p><button className="seo-primary" onClick={onSettings}>Ranking-Verbindung einrichten<ChevronRight size={15}/></button></section>}
  {!config?.keywords.length?<section className="seo-card"><h3>Welche Suchbegriffe sind wichtig?</h3><p>Lege beispielsweise „Porträtshooting Zürich“ an und ordne die passende Leistungsseite zu.</p><p>Trage deine Suchbegriffe oben ein und speichere die Ranking-Einstellungen.</p></section>:<>
   <label className="seo-field">Suchbegriff<select value={keyword?.id||''} onChange={e=>setSelected(e.target.value)}>{config.keywords.map((k:any)=><option key={k.id} value={k.id}>{k.term}</option>)}</select></label>
   <div className="seo-rank-scope"><span>{data.locations[config.location].label}</span><span>{config.device==='mobile'?'Mobil':'Desktop'}</span><span>Deutsch</span><span>Tiefe {config.depth}</span></div>
   <div className="seo-stats"><div><small>Your site · organic position</small><strong>{latest?.position??'—'}{difference!==null&&<em className={difference>=0?'seo-success-text':'seo-danger-text'}>{difference>0?'↑ '+difference:difference<0?'↓ '+Math.abs(difference):'unverändert'}</em>}</strong><span>{latest?(latest.position?'Domain in Google-Suchergebnissen gefunden':`Unter den ${latest.organicCount} gelieferten Ergebnissen nicht gefunden. Eine Position dahinter ist nicht bekannt.`):'Noch keine Messung vorhanden'}</span></div><div><small>Gemessene Ergebnisse</small><strong>{latest?.organicCount??'—'}</strong><span>{date(latest?.at)}</span></div></div>
   <p className="seo-footnote">{config.rankDaily?`Automatik: alle ${config.rankIntervalDays||1} Tage. Nächste Abfrage: ${schedule?.nextAt?date(schedule.nextAt):'beim nächsten Hintergrundlauf'}.`:'Automatische Ranking-Abfragen sind pausiert.'}</p>
   {latest&&<SeoCost cost={latest.cost} legacyAmount={latest.costUsd}/>}
   <button className="seo-primary seo-wide" disabled={!!busy||!data.connected||measuredToday} onClick={()=>act('Google-Ranking messen',()=>request('monitor/rank',{id:keyword.id}),'Google-Messung gespeichert.')}><Search size={16}/>{measuredToday?'Heute bereits gemessen':'Google-Position jetzt messen'}</button>{measuredToday&&<div className="seo-notice" role="status">Die heutige Messung ist gespeichert. Zum Schutz vor doppelten Kosten ist die nächste manuelle Abfrage ab {date(nextManual)} möglich (deine Ortszeit). Das gespeicherte Ergebnis kannst du jederzeit kostenlos ansehen.</div>}<p className="seo-footnote">Kostenpflichtige DataForSEO-Abfrage, maximal einmal täglich je Suchbegriff und Messprofil; insgesamt höchstens 20 Abfragen pro Tag. Keine Anzeigen oder Maps-Positionen.</p>
   <section className="seo-card"><div className="seo-card-title"><TrendingUp size={18}/><h3>Ranking-Verlauf</h3></div><MetricChart ranking depth={config.depth} points={[...records].reverse().slice(-60).map((r:any)=>({at:r.at,value:r.position}))}/><details><summary>Kosten je Ranking-Messung</summary><table className="seo-cost-table"><thead><tr><th>Zeitpunkt</th><th>Position</th><th>Kosten (Anbieter)</th></tr></thead><tbody>{records.map((r:any)=><tr key={r.id}><td>{date(r.at)}</td><td>{r.position??"Nicht gefunden"}</td><td>{typeof r.costUsd==='number'?usd(r.costUsd):'Unbekannt'}</td></tr>)}</tbody></table></details><small>Kleinere Zahl = bessere Position. Fehlende Treffer bleiben Lücken und werden nicht als Position 101 dargestellt.</small></section>
   {latest&&<><section className="seo-card"><div className="seo-card-title"><h3>Die organischen Top 10</h3><span className="seo-chip">DataForSEO / Google</span></div><p>Gemessen in {latest.locationLabel}, {latest.device==='mobile'?'mobil':'am Desktop'}, am {date(latest.at)}. Eine Momentaufnahme; individuelle Suchergebnisse können abweichen.</p><ol className="seo-competitors">{latest.top10.map((r:any)=><li key={r.position} className={r.own?'seo-own-result':''}><span className="seo-rank-number">{r.position}</span><div><small>{r.domain}{r.own?' · DEINE WEBSEITE':''}</small><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title}<ArrowUpRight size={12}/></a><p>{r.description}</p><small>{r.title.length} Titelzeichen · {r.description.length} Snippetzeichen</small></div></li>)}</ol>{latest.checkUrl&&<a href={latest.checkUrl} target="_blank" rel="noopener noreferrer" className="seo-source">Google-Suche öffnen<ArrowUpRight size={12}/></a>}<small>Google kann Titel und Snippets selbst umschreiben. Diese Werte sind keine Messung der tatsächlichen Meta-Tags der Konkurrenzseiten.</small></section>
   <section className="seo-card seo-highlight"><h3>Vergleich mit deiner Zielseite</h3><p>{keyword.path}</p>{ownTitle?<div className="seo-search-preview"><h4>{ownTitle}</h4><p>{ownDescription||'Keine Beschreibung erfasst.'}</p></div>:<p>Öffne die Zielseite und erfasse sie unter „Seiten“, damit die KI ihren aktuellen Inhalt vergleichen kann.</p>}<p>Die nächste KI-Analyse für diese Seite berücksichtigt die gemessenen Top-10-Titel, Such-Snippets und Positionen. Sie vergleicht Suchintention und Themenabdeckung, ohne Konkurrenztexte zu kopieren.</p><button className="seo-primary" onClick={()=>onAnalyze(keyword.path)}>Zielseite analysieren<ChevronRight size={15}/></button></section></>}
  </>}
 </>;
}
export function SeoMonitoringSettings({data,busy,request,act,pages}:Shared&{pages:any[]}){
 const [form,setForm]=useState<any>(data?.config),[login,setLogin]=useState(''),[password,setPassword]=useState('');
 useEffect(()=>{setForm(data?.config);},[data?.config]);
 if(!form)return null;

 return <><section className="seo-card"><div className="seo-card-title"><KeyRound size={19}/><h3>Google-Ranking-Daten</h3><span className="seo-chip">{data.connected?(data.connection?.ok?'Zugang bestätigt':data.connection?'Test fehlgeschlagen':'Noch nicht getestet'):'Nicht verbunden'}</span></div><p>DataForSEO liefert standortbezogene Google-Ergebnisse. Ein separater Account mit API-Guthaben ist erforderlich. Der OpenAI-Schlüssel wird dafür nicht verwendet.</p><a className="seo-source" href="https://app.dataforseo.com/api-access" target="_blank" rel="noopener noreferrer">DataForSEO API-Zugang öffnen<ArrowUpRight size={12}/></a><label className="seo-field">DataForSEO API-Login<input autoComplete="off" value={login} onChange={e=>setLogin(e.target.value)} placeholder="API-Login"/></label><label className="seo-field">DataForSEO API-Passwort<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="seo-actions"><button className="seo-primary" disabled={!!busy||!login.trim()||!password} onClick={()=>act('Ranking-Zugang speichern',async()=>{await request('monitor/credential',{login,password},'PUT');setLogin('');setPassword('');},'Ranking-Zugang verschlüsselt gespeichert. Du kannst die Verbindung jetzt direkt hier testen.')}><ShieldCheck size={15}/>Verschlüsselt speichern</button>{data.connected&&<button className="seo-secondary" disabled={!!busy} onClick={()=>act('Ranking-Zugang entfernen',()=>request('monitor/credential',undefined,'DELETE'),'Ranking-Zugang entfernt. Automatische Messungen pausiert.')}>Entfernen</button>}</div><button className="seo-secondary seo-wide" disabled={!!busy||!data.connected} onClick={()=>act('DataForSEO-Verbindung testen',()=>request('monitor/test',{}),'Verbindungstest abgeschlossen. Ergebnis siehe unten.')}><Activity size={16}/>DataForSEO-Verbindung testen</button><small>Prüft die gespeicherten API-Zugangsdaten und das Guthaben. Startet keine kostenpflichtige Google-Ranking-Abfrage und verbraucht kein Ranking-Tageslimit.</small>{data.connection&&<div className={`seo-notice ${data.connection.ok?'':'seo-error'}`} role="status"><div><strong>{data.connection.ok?'Verbindung bestätigt':'Verbindung nicht bestätigt'}</strong><p>{data.connection.message}</p>{data.connection.ok&&<p>Guthaben: {typeof data.connection.balanceUsd==='number'?`${data.connection.balanceUsd.toFixed(2)} USD`:'Nicht übermittelt'}{data.connection.balanceUsd!==null&&data.connection.balanceUsd<=0?' · Bitte vor einer Ranking-Messung aufladen.':''}</p>}<small>Letzter Test: {date(data.connection.at)}</small><SeoCost cost={data.connection.cost}/></div></div>}<RankingAccessNotice data={data}/><small>Eine erfolgreiche Kontoabfrage bestätigt Zugang und Erreichbarkeit. Ob Google-Rankings freigeschaltet sind, prüft danach eine echte Messung unter „Rankings“. Erst nach erfolgreicher Ranking-Messung lässt sich die automatische Messung aktivieren.</small></section>
 <section className="seo-card"><h3>Website-Checks</h3><label className="seo-toggle"><input type="checkbox" checked={form.healthDaily} onChange={e=>setForm({...form,healthDaily:e.target.checked})}/><span>Website-Gesundheit täglich prüfen<small>Öffentliche Seiten im mobilen VPS-Browser. Keine zusätzliche KI- oder Ranking-API-Gebühr.</small></span></label><button className="seo-secondary" disabled={!!busy} onClick={()=>act('Website-Checks speichern',()=>request('monitor/config',{...data.config,healthDaily:form.healthDaily},'PUT'),'Website-Checks gespeichert.')}>Website-Checks speichern</button></section>
 <p className="seo-footnote">Search Console ist noch nicht verbunden. Klicks, Impressionen und die durchschnittliche Google-Position aus deiner Property werden hier deshalb nicht angezeigt. Gemessene SERP-Positionen sind davon getrennte Momentaufnahmen.</p></>;
}

function SeoRankingSettings({data,busy,request,act,pages}:Shared&{pages:any[]}){
 const [form,setForm]=useState<any>(data?.config);
 useEffect(()=>{setForm(data?.config);},[data?.config]);
 if(!form)return null;
 const availablePaths=[...new Set(['/',...pages.map(p=>p.path),...(data.health?.[0]?.pages||[]).map((p:any)=>p.path)])] as string[];
 return <> <section className="seo-card"><div className="seo-card-title"><Globe2 size={18}/><h3>Suchbegriffe & Ranking-Einstellungen</h3></div><div className="seo-form-grid"><label className="seo-field">Suchstandort<select value={form.location} onChange={e=>setForm({...form,location:e.target.value})}>{Object.entries(data.locations).map(([id,l]:any)=><option key={id} value={id}>{l.label}</option>)}</select></label><label className="seo-field">Gerät<select value={form.device} onChange={e=>setForm({...form,device:e.target.value})}><option value="mobile">Mobil</option><option value="desktop">Desktop</option></select></label></div><label className="seo-field">Ergebnistiefe<select value={form.depth} onChange={e=>setForm({...form,depth:Number(e.target.value)})}><option value={10}>10 Ergebnisse</option><option value={20}>20 Ergebnisse</option><option value={100}>100 Ergebnisse · höhere Abfragekosten</option></select></label><p className="seo-footnote">Google Schweiz, Sprache Deutsch. Positionen verschiedener Standorte, Geräte oder Messtiefen werden als getrennte Verläufe geführt.</p>
 <div className="seo-keyword-editor">{form.keywords.map((k:any,i:number)=><div key={i}><label className="seo-field">Suchbegriff {i+1}<input maxLength={80} value={k.term} placeholder="z. B. Porträtshooting Zürich" onChange={e=>setForm({...form,keywords:form.keywords.map((v:any,j:number)=>i===j?{...v,term:e.target.value}:v)})}/></label><div className="seo-keyword-target"><label className="seo-field">Passende Zielseite<select value={k.path} onChange={e=>setForm({...form,keywords:form.keywords.map((v:any,j:number)=>i===j?{...v,path:e.target.value}:v)})}>{availablePaths.map(p=><option key={p} value={p}>{p}</option>)}</select></label><button className="seo-icon" aria-label={`Suchbegriff ${i+1} entfernen`} onClick={()=>setForm({...form,keywords:form.keywords.filter((_:any,j:number)=>i!==j)})}><Trash2 size={16}/></button></div></div>)}</div><button className="seo-secondary" disabled={form.keywords.length>=10} onClick={()=>setForm({...form,keywords:[...form.keywords,{term:'',path:'/'}]})}><Plus size={14}/>Suchbegriff hinzufügen</button>
 <label className="seo-toggle"><input type="checkbox" checked={form.rankDaily} onChange={e=>setForm({...form,rankDaily:e.target.checked})}/><span>Google-Rankings automatisch messen<small>Kostenpflichtig über deinen DataForSEO-Account. Maximal zehn Suchbegriffe pro Durchlauf.</small></span></label><label className="seo-field">Ranking-Intervall in Tagen<input type="number" inputMode="numeric" min="1" max="365" step="1" value={form.rankIntervalDays??1} onChange={e=>setForm({...form,rankIntervalDays:e.target.value===''?'':Number(e.target.value)})}/></label><p className="seo-footnote">Alle {Number.isInteger(form.rankIntervalDays)&&form.rankIntervalDays>0?form.rankIntervalDays:1} Tage prüfen. Beispiele: 1 = täglich, 7 = wöchentlich, 14 = alle zwei Wochen, 30 = alle 30 Tage (kein fester Kalendermonat). Erlaubt: 1–365 Tage.</p><p className="seo-footnote">Der Abstand beginnt je Suchbegriff und Messprofil mit der letzten Ranking-Abfrage, auch bei Fehlern. Manuelle Ranking-Messungen bleiben möglich und verschieben den nächsten automatischen Termin. Ein reiner Verbindungstest verschiebt ihn nicht.</p><button className="seo-primary seo-wide" disabled={!!busy} onClick={()=>act('Ranking-Einstellungen speichern',()=>request('monitor/config',form,'PUT'),'Ranking-Einstellungen gespeichert.')}><Check size={15}/>Ranking-Einstellungen speichern</button></section></>;
}
